config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'  
  resources :users, only: :new 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 private

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <li><%= "#{current_user.nickname}でログイン中" %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
<% else %>
  <p>ログインしていません</p>
  <li><%= link_to 'ログイン', new_user_session_path %></li>
  <li><%= link_to '新規登録', new_user_path %></li>
<% end %>

app/views/users/new.html.erb
<%= link_to "メールアドレスで登録", new_user_registration_path%>